<a href="https://colab.research.google.com/github/jessika2018/Market-Basket-Analysis/blob/main/version2_Item_description_ashrafieh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install mlxtend --upgrade

Requirement already up-to-date: mlxtend in /usr/local/lib/python3.7/dist-packages (0.18.0)
Requirement already satisfied, skipping upgrade: pandas>=0.24.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.1.5)
Requirement already satisfied, skipping upgrade: matplotlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied, skipping upgrade: scipy>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.4.1)
Requirement already satisfied, skipping upgrade: joblib>=0.13.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.0.1)
Requirement already satisfied, skipping upgrade: numpy>=1.16.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.19.5)
Requirement already satisfied, skipping upgrade: scikit-learn>=0.20.3 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (0.22.2.post1)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.7/dist-packages (from mlxtend) (57.0.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.2->mlxtend) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.2->mlxtend) (2018.9)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.2->mlxtend) (1.15.0)

In [ ]:
import mlxtend
print(mlxtend.__version__)

0.18.0

In [ ]:
# pip install squarify

In [ ]:
#Data manipulation libraries
import pandas as pd
import numpy as np
#for market basket analysis (using apriori)
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.frequent_patterns import fpgrowth

#for preprocessing
from mlxtend.preprocessing import TransactionEncoder


#to print all the interactive output without resorting to print, not only the last result.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
df = pd.read_excel("/content/Ashrafieh Sales.xlsx")
# df

In [ ]:

# test_df=pd.DataFrame(data=df, columns=['Item_Description'])

In [ ]:
# intermediate_df = df['Item_Description'].str.split(';', expand=True).stack().str.strip().reset_index(level=1,drop=True)

In [ ]:
# intermediate_df

In [ ]:
# df
subset_df = df.sample(frac=.5)

In [ ]:
# subset_df

In [ ]:
# df2 = subset_df.groupby(by=['Group','Receipt_Number']).agg(text=("Item_Description", lambda x: ";".join(set(x))))
# df2
df2 = subset_df.groupby(by=['Group']).agg(text=("Item_Description", lambda x: ";".join(set(x))))
# df2
# df2=subset_df.groupby("Group").agg({"Item_Description": np.sum, "Receipt_Number": lambda x: x.nunique()})
# df2

In [ ]:
# new_df = df2.iloc[:,0]

In [ ]:
# new_df

In [ ]:
# df2.Item_Description.nunique()

In [ ]:
# df2.text.nunique()

In [ ]:
# df["Group"] = df["Group"].str.lower()

In [ ]:
df2["text"] = df2["text"].str.lower()

In [ ]:
# df2["text"]

In [ ]:
data = list(df2["text"].apply(lambda x:x.split(';')))
# data

In [ ]:
te = TransactionEncoder()
te_data = te.fit(data).transform(data)
df = pd.DataFrame(te_data,columns=te.columns_)
df

    1% CHOCOLATE MILK RTD ASP  ...  ZWAN MORTADELLA OLIVE
0                       False  ...                  False
1                       False  ...                  False
2                       False  ...                  False
3                       False  ...                  False
4                       False  ...                  False
..                        ...  ...                    ...
93                      False  ...                  False
94                      False  ...                  False
95                      False  ...                  False
96                      False  ...                  False
97                      False  ...                  False

[98 rows x 9740 columns]

In [ ]:
# #Visualizations
# %matplotlib inline
# import matplotlib.pyplot as plt
# import seaborn as sns
# sns.set_style("dark")
# import squarify
# import matplotlib

In [ ]:
# ##Lets consider the top 20 items purchased freequently
# r=df.sum(axis=0).sort_values(ascending=False)[:20]
# #altering the figsize
# plt.figure(figsize=(20,10))
# s=sns.barplot(x=r.index,y=r.values)
# s.set_xticklabels(s.get_xticklabels(), rotation=90)

In [ ]:
# # create a color palette, mapped to these values
# my_values=r.values
# cmap = matplotlib.cm.Blues
# mini=min(my_values)
# maxi=max(my_values)
# norm = matplotlib.colors.Normalize(vmin=mini, vmax=maxi)
# colors = [cmap(norm(value)) for value in my_values]


# #treemap of top 20 frequent items
# plt.figure(figsize=(10,10))
# squarify.plot(sizes=r.values, label=r.index, alpha=.7,color=colors)
# plt.title("Tree map of top 20 items")
# plt.axis('off')

In [ ]:
frequent_itemsets = apriori(df,min_support=0.02,use_colnames=True)
frequent_itemsets

     support                                           itemsets
0   0.020408                                      (APPLE JUICE)
1   0.020408                                (ARTICHOKE BOTTOMS)
2   0.020408                                     (BLEACH LEMON)
3   0.020408                                         (BROWNIES)
4   0.020408                                           (CASHEW)
..       ...                                                ...
74  0.020408  (GREEN ASPARAGUS, ARTICHOKE BOTTOMS, FINE GREE...
75  0.020408  (GOLDEN SWEET CORN, ARTICHOKE BOTTOMS, MIXED V...
76  0.020408  (STRAWBERRY CHEESE CAKE, FONDANT AU CHOCOLAT, ...
77  0.020408  (GOLDEN SWEET CORN, FINE GREEN BEANS, GREEN AS...
78  0.020408  (GREEN ASPARAGUS, FINE GREEN BEANS, GOLDEN SWE...

[79 rows x 2 columns]

In [ ]:
res=association_rules(frequent_itemsets,metric="lift",min_threshold=49)
res

             antecedents  ... conviction
0          (APPLE JUICE)  ...        inf
1         (ORANGE JUICE)  ...        inf
2    (ARTICHOKE BOTTOMS)  ...        inf
3     (FINE GREEN BEANS)  ...        inf
4    (GOLDEN SWEET CORN)  ...        inf
..                   ...  ...        ...
219    (GREEN ASPARAGUS)  ...        inf
220   (FINE GREEN BEANS)  ...        inf
221  (GOLDEN SWEET CORN)  ...        inf
222  (ARTICHOKE BOTTOMS)  ...        inf
223   (MIXED VEGETABLES)  ...        inf

[224 rows x 9 columns]

In [ ]:
# frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x:len(x))
# frequent_itemsets

     support                                           itemsets  length
0   0.020408                                      (APPLE JUICE)       1
1   0.020408                                (ARTICHOKE BOTTOMS)       1
2   0.020408                                     (BLEACH LEMON)       1
3   0.020408                                         (BROWNIES)       1
4   0.020408                                           (CASHEW)       1
..       ...                                                ...     ...
74  0.020408  (GREEN ASPARAGUS, ARTICHOKE BOTTOMS, FINE GREE...       4
75  0.020408  (GOLDEN SWEET CORN, ARTICHOKE BOTTOMS, MIXED V...       4
76  0.020408  (STRAWBERRY CHEESE CAKE, FONDANT AU CHOCOLAT, ...       4
77  0.020408  (GOLDEN SWEET CORN, FINE GREEN BEANS, GREEN AS...       4
78  0.020408  (GREEN ASPARAGUS, FINE GREEN BEANS, GOLDEN SWE...       5

[79 rows x 3 columns]

In [ ]:
frequent_itemsets[ (frequent_itemsets['length'] == 5) &
                   (frequent_itemsets['support'] >= 0.02) ]

     support                                           itemsets  length
78  0.020408  (GREEN ASPARAGUS, FINE GREEN BEANS, GOLDEN SWE...       5

In [ ]:
# frequent_itemsets[ (frequent_itemsets['length'] == 1) &
#                    (frequent_itemsets['support'] >= 0.01) ]

In [ ]:
# rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.5)

In [ ]:
frequent_itemset_fp_growth=fpgrowth(df,min_support=0.02,use_colnames=True)
frequent_itemset_fp_growth = frequent_itemset_fp_growth.sort_values(by="support",ascending=False)
frequent_itemset_fp_growth

     support                                           itemsets
20  0.030612                                        (PISTACHIO)
40  0.020408              (ARTICHOKE BOTTOMS, MIXED VEGETABLES)
58  0.020408  (GOLDEN SWEET CORN, FINE GREEN BEANS, MIXED VE...
57  0.020408  (GOLDEN SWEET CORN, ARTICHOKE BOTTOMS, MIXED V...
56  0.020408  (GOLDEN SWEET CORN, FINE GREEN BEANS, GREEN AS...
..       ...                                                ...
26  0.020408                                            (PLUMS)
25  0.020408                                        (HOT SAUCE)
24  0.020408                              (CURRY POWDER MEDIUM)
23  0.020408                           (STRAWBERRY CHEESE CAKE)
78  0.020408                        (APPLE JUICE, ORANGE JUICE)

[79 rows x 2 columns]

In [ ]:
res=association_rules(frequent_itemset_fp_growth,metric="lift",min_threshold=49)
res = res.sort_values(by="lift",ascending=False)
res

                               antecedents  ... conviction
0                      (ARTICHOKE BOTTOMS)  ...        inf
1                       (MIXED VEGETABLES)  ...        inf
142  (GOLDEN SWEET CORN, MIXED VEGETABLES)  ...        inf
143    (GREEN ASPARAGUS, FINE GREEN BEANS)  ...        inf
144   (FINE GREEN BEANS, MIXED VEGETABLES)  ...        inf
..                                     ...  ...        ...
78   (ARTICHOKE BOTTOMS, FINE GREEN BEANS)  ...        inf
79   (ARTICHOKE BOTTOMS, MIXED VEGETABLES)  ...        inf
80    (FINE GREEN BEANS, MIXED VEGETABLES)  ...        inf
81                     (ARTICHOKE BOTTOMS)  ...        inf
223                         (ORANGE JUICE)  ...        inf

[224 rows x 9 columns]

In [ ]:
frequent_itemsets.sort_values(by="support",ascending=False)

     support                                           itemsets  length
32  0.030612                                        (PISTACHIO)       1
0   0.020408                                      (APPLE JUICE)       1
50  0.020408                   (FONDANT AU CHOCOLAT, PISTACHIO)       2
57  0.020408                (STRAWBERRY CHEESE CAKE, PISTACHIO)       2
56  0.020408               (HOMMOS READY TO EAT, HOMMOS TAHINA)       2
..       ...                                                ...     ...
25  0.020408                                          (KETCHUP)       1
24  0.020408                                        (HOT SAUCE)       1
23  0.020408                                    (HOMMOS TAHINA)       1
22  0.020408                              (HOMMOS READY TO EAT)       1
78  0.020408  (GREEN ASPARAGUS, FINE GREEN BEANS, GOLDEN SWE...       5

[79 rows x 3 columns]